server.port=8080

spring.cloud.gateway.enabled=true

spring.cloud.gateway.routes[0].id=student-service-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**

spring.cloud.gateway.routes[1].id=course-service-route
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**